### PR TITLE
Fixed witch hat floating while sneaking

### PR DESCRIPTION
**Pull request by BernardoCBranco**
Before:

After:

### CODE REVIEW

**Comment by BernardoCBranco** [comment]
It's been quite a while and from what I tested the issue is still present. Is something wrong with the PR?

**Comment by BernardoCBranco** [comment]
I shouldn't have rebased... Why is it unable to analyse the PR!? -_-'

**Comment by BernardoCBranco** [comment]
It seems to have passed fine now. @P3pp3rF1y can you give me some feedback?

**Comment by P3pp3rF1y** [comment]
Sorry I wasn't active here as I was busy with other stuff. The change is good so I will include in the next release

**Pull request merged**
