### PR TITLE
Config feature to disable some features 

### PR DESCRIPTION
**Pull request by Lothrazar**
New 'disable' config category

Config features to disable 

- Alkahestry Tome
- Handgun, along with bullets magazines and gun parts
- Potions along with mortar, altar, tipped arrows, powder
- Pedestals
- Passive Pedestals

### CODE REVIEW

**Comment by P3pp3rF1y** [comment]
Looks pretty good to me but I have two style comments:
First you seem to use a different formating. you can find the code format that's used for the rest of the project in https://github.com/P3pp3rF1y/Reliquary/tree/1.12.x/codeformat
And second having enable booleans in "Disabled" category seems confusing to me. How about that gets changed to disableThing = false by default and then you reverse the checks in the code or the category gets renamed to "Enabled" still with the comment that you can disable stuff there?

**Comment by Lothrazar** [comment]
How do i import settings dot jar as a codeformatter? I assume its IDE specific.. but i dont know which one? 

 Looks like the main difference is i have spaces instead of tabs in some places

First ill change the other thing, so it will be "disablePotions = false" in settings, and then ill go back and see if i can figure out the formatter

**Comment by Lothrazar** [comment]
Ok on the code formatter

In intelliJ i went to file-Import Settings and picked your settings.jar in the repo.

Then i right click project and went "Reformat Code"  


But now literally every single file in the whole repo has changed.  even files i didnt even touch 

I guess its doing as intended; its applying your "max length" rule, and using 4 spaces instead of two, changing some spacing of some if statmements and so on

Does this sound right? Screen shot of "git diff"

formatter

json

**Comment by Lothrazar** [comment]
The thing that ran that changed every file.  (not committed or pushed)

like this

**Comment by P3pp3rF1y** [comment]
Ohh, I didn't mean reformat the whole project just the files you're changing. But it also seems like I have changed a few bits in the code style since I last touched some of these files. 
I have just committed a new code style into the repo (this time it's Intellij xml code style file that you import in code style tab directly). 
Just apply that to the files you have changed (Ctrl + Alt + L)

**Comment by Lothrazar** [comment]
Ah thanks for the xml version.

Applied it to all 7 files changed

**Comment by Xorbah** [comment]
So, how can we apply these changes in the original release?

**Pull request merged**
